"""Parity test: kazbars.deeps_parsers must produce identical totals to Deeps's
Rust parsers (aoc-damage + aoc-heal) when run over a real CombatLog file.

The ground truth lives in `tests/fixtures/deeps_parity/expected_totals.json`,
generated by the Rust binary at `Deeps/rust/parity-dump/`. If the Python
parsers ever drift from the Rust source of truth, this test fails with a
clear diff between expected and actual totals.

The CombatLog file itself is not committed (36 MB). The test looks for it
at:
  1. Path in env var `DEEPS_PARITY_LOG`, if set
  2. The default development path used to generate the fixture

If neither path resolves to an existing file, the test is skipped — no
hard dependency on a specific machine.

Regeneration: see the comments in `expected_totals.json`.
"""

import json
import os
from collections import Counter
from pathlib import Path

import pytest

from kazbars.deeps_parsers import (
    HealKind,
    parse_incoming_damage,
    parse_incoming_heal,
    parse_outgoing_damage,
    parse_pet_hit,
    strip_log_timestamp,
)

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "deeps_parity"
EXPECTED_PATH = FIXTURE_DIR / "expected_totals.json"

# Default path used to generate the fixture. The CombatLog itself isn't in
# the repo; override via env var on other machines.
DEFAULT_LOG_PATH = Path(
    r"E:\Game Clients\Age of Conan - mods\CombatLog-2026-05-17_2057.txt"
)


def _resolve_log_path() -> Path | None:
    env = os.environ.get("DEEPS_PARITY_LOG")
    if env:
        p = Path(env)
        return p if p.exists() else None
    return DEFAULT_LOG_PATH if DEFAULT_LOG_PATH.exists() else None


def _process_log(log_path: Path) -> dict:
    """Run every parser over every line, return totals shaped like the fixture."""
    lines_total = 0
    lines_blank = 0
    out_count = 0
    out_total = 0
    in_dmg_count = 0
    in_dmg_total = 0
    heal_total_count = 0
    heal_total_amount = 0
    heal_by_kind: Counter[str] = Counter()
    heal_amount_by_kind: Counter[str] = Counter()
    pet_count = 0
    pet_total = 0

    with open(log_path, encoding="utf-8", errors="replace") as f:
        for raw in f:
            lines_total += 1
            line = raw.rstrip("\r\n")
            line = strip_log_timestamp(line)
            if not line:
                lines_blank += 1
                continue

            dmg_out = parse_outgoing_damage(line)
            if dmg_out is not None:
                out_count += 1
                out_total += dmg_out

            dmg_in = parse_incoming_damage(line)
            if dmg_in is not None:
                in_dmg_count += 1
                in_dmg_total += dmg_in

            heal = parse_incoming_heal(line)
            if heal is not None:
                heal_total_count += 1
                heal_total_amount += heal.amount
                heal_by_kind[heal.kind.value] += 1
                heal_amount_by_kind[heal.kind.value] += heal.amount

            pet_hit = parse_pet_hit(line)
            if pet_hit is not None:
                pet_count += 1
                pet_total += pet_hit

    return {
        "lines_total": lines_total,
        "lines_blank_after_timestamp_strip": lines_blank,
        "outgoing_damage": {"matches": out_count, "total": out_total},
        "incoming_damage": {"matches": in_dmg_count, "total": in_dmg_total},
        "incoming_heal": {
            "matches": heal_total_count,
            "total": heal_total_amount,
            "by_kind": {
                kind.value: {
                    "matches": heal_by_kind[kind.value],
                    "total": heal_amount_by_kind[kind.value],
                }
                for kind in HealKind
            },
        },
        "pet_damage": {"matches": pet_count, "total": pet_total},
    }


@pytest.fixture(scope="module")
def expected() -> dict:
    with open(EXPECTED_PATH, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def actual(expected: dict) -> dict:
    log_path = _resolve_log_path()
    if log_path is None:
        pytest.skip(
            "CombatLog file not found. Set DEEPS_PARITY_LOG to the path of "
            f"'{expected['log_filename']}' to run this test."
        )
    return _process_log(log_path)


def test_lines_total(expected: dict, actual: dict) -> None:
    assert actual["lines_total"] == expected["lines_total"]


def test_lines_blank(expected: dict, actual: dict) -> None:
    assert (
        actual["lines_blank_after_timestamp_strip"]
        == expected["lines_blank_after_timestamp_strip"]
    )


def test_outgoing_damage(expected: dict, actual: dict) -> None:
    assert actual["outgoing_damage"] == expected["outgoing_damage"]


def test_incoming_damage(expected: dict, actual: dict) -> None:
    assert actual["incoming_damage"] == expected["incoming_damage"]


def test_incoming_heal_aggregate(expected: dict, actual: dict) -> None:
    assert actual["incoming_heal"]["matches"] == expected["incoming_heal"]["matches"]
    assert actual["incoming_heal"]["total"] == expected["incoming_heal"]["total"]


@pytest.mark.parametrize("kind", ["spell", "potion", "health_tap"])
def test_incoming_heal_by_kind(expected: dict, actual: dict, kind: str) -> None:
    assert (
        actual["incoming_heal"]["by_kind"][kind]
        == expected["incoming_heal"]["by_kind"][kind]
    )


def test_pet_damage(expected: dict, actual: dict) -> None:
    assert actual["pet_damage"] == expected["pet_damage"]
