"""
KazBars — KzGrids Code Generator
Generates KzGrids.as ActionScript 2.0 source code from grid configurations.
"""

import logging
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

from .build_utils import compile_as2, resolve_assets_path
from .grid_model import MAX_TOTAL_SLOTS

logger = logging.getLogger(__name__)


_template_cache = {}

def _load_core_template(assets_path=None):
    """Load AS2 core methods template from external file (cached)."""
    base = resolve_assets_path(assets_path)
    template_path = base / "kazbars" / "KzGrids_core.as.template"
    key = str(template_path)
    if key not in _template_cache:
        with open(template_path, encoding='utf-8') as f:
            _template_cache[key] = f.read()
    return _template_cache[key]

# ============================================================================
# CODE GENERATOR
# ============================================================================
class CodeGenerator:
    """Generate AS2 source code for the KazBars buff-tracking grid system."""

    def __init__(self, grids, database, app_version, assets_path=None, include_console=False):
        """Initialize the code generator with grid configs and the buff database."""
        # Filter out disabled grids
        self.grids = [g for g in grids if g.get('enabled', True)]
        self.database = database
        self.app_version = app_version
        self._assets_path = assets_path
        self._stack_labels = {}
        self.include_console = include_console

    def sanitize_id(self, grid_id):
        """Convert a grid ID to a safe AS2 identifier by replacing invalid characters."""
        safe = ""
        for c in grid_id:
            if c.isalnum() or c == '_':
                safe += c
            else:
                safe += '_'
        if safe and safe[0].isdigit():
            safe = '_' + safe
        return safe or "Grid"

    def generate(self):
        """Generate the main KzGrids.as and separate KzGridsData.as source code."""
        # Main class (no inline config — calls KzGridsData.init())
        main = []
        main.append(self._header())
        main.append(self._class_start())
        main.append(self._member_variables())
        main.append(self._constructor())
        main.append(self._init_config_stub())
        main.append(self._core_methods())
        main.append(self._class_end())

        # Data class (all grid configs, whitelists, buff lookups)
        data = []
        data.append(self._header())
        data.append(self._data_class())

        return '\n'.join(main), '\n'.join(data)

    def _header(self):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        total_slots = sum(g['rows'] * g['cols'] for g in self.grids)
        return f'''// ============================================================================
// KZGRIDS - Generated by KazBars v{self.app_version}
// Generated: {timestamp}
// Total slots: {total_slots} / {MAX_TOTAL_SLOTS}
// ============================================================================
'''

    def _class_start(self):
        return 'class KzGrids {\n'

    def _class_end(self):
        return '}\n'

    def _member_variables(self):
        console_decl = '\n    private var console:KzGridsConsole;' if self.include_console else ''
        console_pin_decl = '\n\n    // Console pin state (persisted via config archive)\n    private var consolePinned:Boolean;' if self.include_console else ''
        return f'''
    private var rootClip:MovieClip;
    private var m_Player:Object;
    private var m_Target:Object;
    private var config:Object;
    private var playerBuffs:Array;
    private var targetBuffs:Array;
    private var buffIndexCache:Object;
    private var grids:Array;
    private var timerInterval:Number;
    private var frameActive:Boolean;
    private var frameCount:Number;
    private var TCACHE:Object;
    private var previewMode:Boolean;
    private var previewArmed:Boolean;
    private var lastShiftDown:Number;
    private var lastCtrlDown:Number;
    private var lastAltDown:Number;
    private var C_BUFF:Number;
    private var C_DEBUFF:Number;
    private var C_BG:Number;
    private var CFG:Object;
    private var WL:Object;
    private var ISDEB:Object;
    private var BUFFTYPE:Object;
    private var STACK_LEVEL:Object;

    // OPTIMIZATION: Alpha flash lookup table (100 pre-calculated values)
    private var AFLASH:Array;

    // OPTIMIZATION: Reusable arrays to reduce GC
    private var _tempBuffs:Array;
    private var _tempDebuffs:Array;
    private var _tempMisc:Array;

    // HELPER CLASSES: Preview, Slot, and (optional) Console (32KB bytecode limit workaround)
    private var preview:KzGridsPreview;{console_decl}
    private var slot:KzGridsSlot;{console_pin_decl}

    // Key listener reference for proper cleanup
    private var keyListener:Object;
'''

    def _constructor(self):
        console_pin_init = '\n        consolePinned = false;' if self.include_console else ''
        console_init = '\n        console = new KzGridsConsole(this, rootClip);' if self.include_console else ''
        return f'''
    public function KzGrids(root:MovieClip) {{
        rootClip = root;
        playerBuffs = new Array();
        targetBuffs = new Array();
        grids = new Array();
        buffIndexCache = {{player: {{}}, target: {{}}}};
        frameActive = false;
        frameCount = 0;
        previewMode = false;
        previewArmed = true;
        lastShiftDown = 0;
        lastCtrlDown = 0;
        lastAltDown = 0;{console_pin_init}
        C_BUFF = 0x666666;
        C_DEBUFF = 0x8B0000;
        C_BG = 0x000000;
        TCACHE = {{}};
        var i:Number = 0;
        while (i <= 99) {{ TCACHE[i] = String(i); i++; }}

        // OPTIMIZATION: Pre-calculate alpha flash values (100 entries)
        // Replaces Math.sin() calls every frame with array lookup
        AFLASH = new Array();
        var j:Number = 0;
        while (j < 100) {{
            var phase:Number = (j / 100) * 6.28318;
            AFLASH[j] = 33 + (Math.sin(phase) + 1) * 33.5;
            j++;
        }}

        // OPTIMIZATION: Reusable arrays to reduce garbage collection
        _tempBuffs = new Array();
        _tempDebuffs = new Array();
        _tempMisc = new Array();

        // HELPER CLASSES: Initialize preview and slot managers (console added if enabled at build time)
        preview = new KzGridsPreview(this, rootClip);{console_init}
        slot = new KzGridsSlot(this, rootClip);

        initConfig();
    }}
'''

    def _expand_primary_ids(self, primary_ids):
        """Expand primary spell IDs to full ID lists (respecting stacking)."""
        ids = []
        for pid in primary_ids:
            entry = self.database.by_id.get(pid)
            if entry:
                entry_ids = entry.get('ids', [])
                if entry.get('stacking', False):
                    start = entry.get('stackStart', 1)
                    if entry.get('partialList', False):
                        for i, bid in enumerate(entry_ids):
                            self._stack_labels[bid] = start + i
                    else:
                        end = entry.get('stackEnd', 0) or len(entry_ids)
                        filtered = entry_ids[start - 1:end]
                        for i, bid in enumerate(filtered):
                            self._stack_labels[bid] = start + i
                        entry_ids = filtered
                ids.extend(entry_ids)
            else:
                logger.warning("Primary ID %d not in database — skipped", pid)

        seen = set()
        result = []
        for bid in ids:
            if bid not in seen:
                seen.add(bid)
                result.append(bid)
        return sorted(result)

    def _resolve_grid(self, grid):
        resolved = dict(grid)
        whitelist = grid.get('whitelist', [])
        if whitelist:
            resolved['whitelist'] = self._expand_primary_ids(whitelist)
        slot_assignments = grid.get('slotAssignments', {})
        if slot_assignments:
            resolved_sa = {}
            for k, v in slot_assignments.items():
                if v:
                    resolved_sa[k] = self._expand_primary_ids(v)
                else:
                    resolved_sa[k] = v
            resolved['slotAssignments'] = resolved_sa
        return resolved

    def _init_config_stub(self):
        return '''
    private function initConfig():Void {
        var d:Object = KzGridsData.init();
        CFG = d.CFG;
        WL = d.WL;
        ISDEB = d.ISDEB;
        BUFFTYPE = d.BUFFTYPE;
        STACK_LEVEL = d.STACK_LEVEL;
    }'''

    def _data_class(self):
        lines = ['''class KzGridsData {

    public static function init():Object {
        var d:Object = {};
        d.CFG = {};
        d.CFG.grids = new Array();
        d.WL = {};
        d.ISDEB = {};
        d.BUFFTYPE = {};
        d.STACK_LEVEL = {};
        var i:Number;
''']

        all_buff_ids = set()
        for idx, grid in enumerate(self.grids):
            resolved = self._resolve_grid(grid)
            lines.append(self._generate_grid_config(resolved, idx, var_prefix='d.'))
            for bid in resolved.get('whitelist', []):
                all_buff_ids.add(bid)
            for slot_ids in resolved.get('slotAssignments', {}).values():
                for bid in slot_ids:
                    all_buff_ids.add(bid)

        if all_buff_ids:
            lines.append('\n        // Debuff, Type, and Stack Level lookup')
            for bid in sorted(all_buff_ids):
                is_deb = "true" if self.database.is_debuff(bid) else "false"
                buff_type = self.database.get_type(bid)
                lines.append(f'        d.ISDEB[{bid}] = {is_deb};')
                lines.append(f'        d.BUFFTYPE[{bid}] = "{buff_type}";')
                stack_level = self._stack_labels.get(bid)
                if stack_level is not None:
                    lines.append(f'        d.STACK_LEVEL[{bid}] = {stack_level};')

        lines.append('        return d;')
        lines.append('    }')
        lines.append('}')
        return '\n'.join(lines)

    def _generate_grid_config(self, grid, idx, var_prefix=''):
        gid = grid['id']
        vid = f"{self.sanitize_id(gid)}_{idx}"
        cfg = f'{var_prefix}CFG'
        wl = f'{var_prefix}WL'
        lines = []

        lines.append(f'''
        // {gid}
        var {vid}:Object = {{
            id: "{gid}",
            type: "{grid['type']}",
            rows: {grid['rows']},
            cols: {grid['cols']},
            iconSize: {grid['iconSize']},
            gap: {grid['gap']},
            x: {grid['x']},
            y: {grid['y']},
            slotMode: "{grid['slotMode']}",
            fillDir: "{grid['fillDirection']}",
            sortOrder: "{grid['sortOrder']}",
            layout: "{grid['layout']}",
            showTimers: {'true' if grid['showTimers'] else 'false'},
            timerFont: {grid.get('timerFontSize', 18)},
            timerFlashThreshold: {grid.get('timerFlashThreshold', 6)},
            timerYOffset: {grid.get('timerYOffset', 0)},
            stackFont: {grid.get('stackFontSize', 14)},
            enableFlashing: {'true' if grid.get('enableFlashing', True) else 'false'}''')

        if grid['slotMode'] == 'static':
            lines[-1] += ',\n            slots: {}\n        };'
            for slot_idx, buff_ids in grid.get('slotAssignments', {}).items():
                if buff_ids:
                    ids_str = ', '.join(str(bid) for bid in buff_ids)
                    lines.append(f'        {vid}.slots[{int(slot_idx)}] = [{ids_str}];')
        else:
            lines[-1] += '\n        };'

        lines.append(f'        {cfg}.grids.push({vid});')

        whitelist = grid.get('whitelist', [])
        if whitelist or grid['slotMode'] == 'dynamic':
            lines.append(f'\n        {wl}["{gid}"] = {{}};')
            if whitelist:
                ids_str = ', '.join(str(bid) for bid in whitelist)
                lines.append(f'        var {vid}_ids:Array = [{ids_str}];')
                lines.append(f'''        i = 0;
        while (i < {vid}_ids.length) {{
            {wl}["{gid}"][{vid}_ids[i]] = true;
            i++;
        }}''')

        if grid['slotMode'] == 'static':
            all_ids = set()
            for slot_ids in grid.get('slotAssignments', {}).values():
                all_ids.update(slot_ids)
            if all_ids:
                lines.append(f'\n        {wl}["{gid}"] = {{}};')
                for bid in sorted(all_ids):
                    lines.append(f'        {wl}["{gid}"][{bid}] = true;')

        return '\n'.join(lines)

    def _core_methods(self):
        template = _load_core_template(self._assets_path)
        if self.include_console:
            tokens = {
                '{{CONSOLE_LOG_PLAYER}}':
                    'if (console.isActive() && buff.m_Name != null) console.logPlayer(buff.m_Name, bid);',
                '{{CONSOLE_LOG_TARGET}}':
                    'if (console.isActive() && buff.m_Name != null) console.logTarget(buff.m_Name, bid);',
                '{{CONSOLE_PREVIEW_OPEN}}':
                    'if (!console.isActive()) console.createConsole();',
                '{{CONSOLE_EXIT_PERSIST}}':
                    'config.ReplaceEntry("console_pin", consolePinned ? 1 : 0);\n'
                    '            config.ReplaceEntry("log_p", console.logPlayerEnabled ? 1 : 0);\n'
                    '            config.ReplaceEntry("log_t", console.logTargetEnabled ? 1 : 0);',
                '{{CONSOLE_EXIT_REMOVE}}':
                    'if (!consolePinned) console.removeConsole();',
                '{{CONSOLE_CLEANUP}}':
                    'console.removeConsole();',
                '{{CONSOLE_LOAD_PERSIST}}':
                    'var cp:Object = config.FindEntry("console_pin");\n'
                    '            if (cp !== undefined) consolePinned = (cp == 1);\n'
                    '            var clp:Object = config.FindEntry("log_p");\n'
                    '            if (clp !== undefined) console.logPlayerEnabled = (clp == 1);\n'
                    '            var clt:Object = config.FindEntry("log_t");\n'
                    '            if (clt !== undefined) console.logTargetEnabled = (clt == 1);\n'
                    '            if (consolePinned) console.createConsole();',
                '{{CONSOLE_DEACTIVATE_PERSIST}}':
                    'config.ReplaceEntry("console_pin", consolePinned ? 1 : 0);\n'
                    '            config.ReplaceEntry("log_p", console.logPlayerEnabled ? 1 : 0);\n'
                    '            config.ReplaceEntry("log_t", console.logTargetEnabled ? 1 : 0);',
            }
        else:
            tokens = {
                '{{CONSOLE_LOG_PLAYER}}': '',
                '{{CONSOLE_LOG_TARGET}}': '',
                '{{CONSOLE_PREVIEW_OPEN}}': '',
                '{{CONSOLE_EXIT_PERSIST}}': '',
                '{{CONSOLE_EXIT_REMOVE}}': '',
                '{{CONSOLE_CLEANUP}}': '',
                '{{CONSOLE_LOAD_PERSIST}}': '',
                '{{CONSOLE_DEACTIVATE_PERSIST}}': '',
            }
        for token, replacement in tokens.items():
            template = template.replace(token, replacement)
        return template


# ============================================================================
# BUILD FUNCTION
# ============================================================================
def build_grids(
    grids: list,
    database,
    base_swf: str,
    stubs_path: str,
    output_swf: str,
    compiler_path: str,
    app_version: str = "3.6.0",
    assets_path=None,
    include_console: bool = False,
) -> tuple[bool, str]:
    """
    Complete build process for KazBars.swf.

    Args:
        grids: List of grid configuration dicts
        database: BuffDatabase instance
        base_swf: Path to assets/kazbars/base.swf
        stubs_path: Path to assets/kazbars/stubs/
        output_swf: Path to write final KazBars.swf
        compiler_path: Path to mtasc.exe
        app_version: Version string for header comment

    Returns:
        (success: bool, message: str)
    """
    base_swf = Path(base_swf)
    stubs_path = Path(stubs_path)
    output_swf = Path(output_swf)
    compiler_path = Path(compiler_path)

    if not base_swf.exists():
        return False, f"KazBars base.swf not found:\n{base_swf}"
    if not compiler_path.exists():
        return False, f"MTASC compiler not found:\n{compiler_path}"

    temp_dir = None
    try:
        # Step 1: Generate AS2 code (main class + data class)
        generator = CodeGenerator(grids, database, app_version, assets_path=assets_path, include_console=include_console)
        main_code, data_code = generator.generate()

        # Step 2: Write to temp .as files
        temp_dir = tempfile.mkdtemp(prefix="kazbars_")
        temp_main_as = Path(temp_dir) / "KzGrids.as"
        temp_data_as = Path(temp_dir) / "KzGridsData.as"
        with open(temp_main_as, 'w', encoding='utf-8') as f:
            f.write(main_code)
        with open(temp_data_as, 'w', encoding='utf-8') as f:
            f.write(data_code)

        # Step 3: Copy base.swf to temp
        output_swf.parent.mkdir(parents=True, exist_ok=True)
        temp_swf = Path(temp_dir) / "KazBars.swf"
        shutil.copy2(base_swf, temp_swf)

        # Step 4: Compile (both main class and data class)
        common_stubs = base_swf.parent.parent / "common_stubs"
        ok, err = compile_as2(compiler_path, [stubs_path, common_stubs, temp_dir], temp_swf, [temp_main_as, temp_data_as], temp_dir)
        if not ok:
            return False, f"MTASC compilation failed:\n{err}"

        # Step 5: Copy to game directory
        shutil.copy2(temp_swf, output_swf)

        output_size = output_swf.stat().st_size
        return True, f"KazBars.swf built successfully ({output_size:,} bytes)"

    except Exception as e:
        logger.exception("build_grids failed")
        return False, f"Build error: {e!s}"
    finally:
        if temp_dir:
            try:
                shutil.rmtree(temp_dir)
            except OSError as cleanup_err:
                logger.warning("temp dir cleanup failed: %s", cleanup_err)
