"""Regenerate docs/inventory.md's line-count table from the file tree.

Walks src/kazbars/*.py and tests/*.py and rewrites the whole table with
current path + line count. Role blurbs live in docs/inventory-roles.md and
are not touched here — this file is a machine-checked skeleton.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC = REPO_ROOT / 'docs' / 'inventory.md'

HEADER = '''# File inventory

**Purpose:** one row per `src/kazbars/*.py` and `tests/*.py` file — path, line count. Generated by `scripts/gen_inventory.py`; re-run on any tracked `.py` change via pre-commit. Per-file role and behavior notes live in [`inventory-roles.md`](inventory-roles.md). Machine-checked by `tests/test_docs_in_sync.py`: no phantoms, no omissions, exact line counts. Module topology and clusters live in [`architecture.md`](architecture.md).

> Never add another table row shaped `| src/kazbars/x.py | <number> | …` to any other
> doc — the row regex scans every line of this file only, but a stray match elsewhere
> would go unnoticed. This table is generated; edit `scripts/gen_inventory.py`, not
> the rows.

## Files

| File | Lines |
|---|---:|
'''


def _lines(path):
    # Count '\n' bytes to match `wc -l` regardless of line endings.
    return path.read_bytes().count(b'\n')


def _rows():
    rows = []
    for sub in ('src/kazbars', 'tests'):
        for p in sorted((REPO_ROOT / sub).glob('*.py'), key=lambda p: p.name):
            rel = f'{sub}/{p.name}'
            rows.append(f'| `{rel}` | {_lines(p)} |')
    return rows


def main():
    body = HEADER + '\n'.join(_rows()) + '\n'
    DOC.write_text(body, encoding='utf-8')


if __name__ == '__main__':
    main()
